'use strict';

var config = require('./config');
var exec = require('sync-exec');
var fs = require('fs');
var path = require('path');

function rel(relPath) {
  return path.join(__dirname, relPath);
}

// build
require('./build');

// set CNAME
if (config.host) {
  fs.writeFileSync(rel('build/CNAME'), config.host);
}

[
  'git init',
  'git remote add origin ' + config.repo,
  'git add .',
  'git commit -m "generated by rin."',
  'git push origin master:gh-pages --force',
].forEach(function (cm) {
  var result = exec(cm, {cwd: rel('build')});
  if (result.stdout) {
    console.log(result.stdout);
  }
  if (result.stderr) {
    console.error(result.stderr);
  }
});
